version: '3.8'

services:

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hlstatsxce
      MYSQL_USER: hlstatsxce
      MYSQL_PASSWORD: hlstatsxce
    volumes:
      - db-volume:/var/lib/mysql
      - ./src/sql/install.sql:/docker-entrypoint-initdb.d/01-install.sql:ro
    networks:
      - default

  daemon:
    build:
      context: .
      dockerfile: Dockerfile.daemon
      target: dev
      args:
        DEBIAN_VERSION: bookworm
    ports:
      - 27500:27500/udp
    networks:
      - default
    depends_on:
      - db
    command:
      - --ip=0.0.0.0
      - --port=27500
      - --db-host=db:3306
      - --db-name=hlstatsxce
      - --db-username=hlstatsxce
      - --db-password=hlstatsxce
      - --nodns-resolveip
      - --debug

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      target: dev
    ports:
      - 8081:80
    environment:
      DB_ADDR: db
      DB_NAME: hlstatsxce
      DB_USER: hlstatsxce
      DB_PASS: hlstatsxce
    volumes:
      - ./src/web:/web
    depends_on:
      - db
      - init-container
    networks:
      - default
    extra_hosts:
      - host.docker.internal:host-gateway

  phpmyadmin:
    image: phpmyadmin:5.2
    environment:
      PMA_HOST: db
    ports:
      - 8083:80
    networks:
      - default

  init-container:
    image: alpine:latest
    volumes:
      - ./src/web:/web
      - db-volume:/var/lib/mysql
    networks:
      - default
    entrypoint:
      - /bin/sh
    command:
      - -c
      - |
          set -eu
          echo "Granting web nginx and php read permissions"
          find /web -type d -exec chmod 755 {} \;
          find /web -type f -exec chmod 644 {} \;
          echo "Granting web php write permissions"
          chmod 777 /web/hlstatsimg/progress
          chmod 777 /web/hlstatsimg/graph
          echo "Granting db write permissions"
          chown -R 999:999 /var/lib/mysql

volumes:
  db-volume:

networks:
  default:
    driver: bridge
